name: "Setup other actions"
description: "Initialize environment and install dependencies for other actions"

runs:
  using: "composite"
  steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        cache: "yarn"

    - name: Install yarn
      shell: bash
      run: npm install yarn -g

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile  --ignore-engines
