name: 'Setup other actions'
description: 'Initialize environment and install dependencies for other actions'

runs:
  using: 'composite'
  steps:
    -  name: Checkout
       shell: bash
       uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: install dependencies
      shell: bash
      run: yarn install --frozen-lockfile  --ignore-engines

