name: push-main

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Check code quality
        shell: bash
        run: yarn run lint:check

      - name: Check formatting
        shell: bash
        run: yarn run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/actions/setup/

      - name: Test and report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
