name: push-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/actions/setup/

      - name: Check code quality
        shell: bash
        run: yarn run lint:check

      - name: Check formatting
        shell: bash
        run: yarn run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/actions/setup/

      - name: test and report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn

  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/actions/setup/

      - name: Build the app
        shell: bash
        run: yarn run build
