# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: push-main
defaults:
  run:
    shell: bash
on:
  push:
    branches: ['main']
jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Check code quality
        run: yarn run lint

      - name: Check formatting
        run: yarn run format:check

      - name: Run the tests
        run: yarn run test:ci

      - name: Build the app
        run: npm run build
